services:
  postgres:
    image: postgres:15-alpine
    container_name: url-shortener-postgres-1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=urlshortener
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d urlshortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: url-shortener-app-1
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=urlshortener
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy # This prevents the app from crashing while PG boots